### ISSUE TITLE
Show Exception stack traces in grader output

### ISSUE THREAD

**Issue by benhannel** [tkutcher/jgrade#19]
**Is your feature request related to a problem? Please describe.**
Currently, if a test throws an exception, but there is no line number or stack trace. It would really help our students debug if the default output was more verbose. If you could even point me to where this behavior is happening, I could make the necessary changes myself.

**Describe the solution you'd like**
The default string conversion of an error message should be a full stack trace, rather than simply the message.

**Describe alternatives you've considered**
We could modify our own tests to catch all exceptions, print their stack traces as a string, and then throw them back up, but that seems hacky.

**Additional context**
Here's some example output. You can see there's an out of bound exception, but with no clear way to find the source:
```
{"tests": [
  {
    "output": "TEST FAILED.\nRange [22, 22 + 100) out of bounds for length 100\nReading 0, 15232128\nByteBuffer get 22, 100, 128\n",
    "score": 0,
    "number": "4",
    "visibility": "visible",
    "max_score": 5,
    "name": "TestRecoveryPerformance2"
  },
```

**Comment by tkutcher** [comment]
Hi there!

Terribly sorry I had no idea I was missing notifications for this project. Although I'm wondering now if the semester's over if I'm too late in my reply. In general, definitely interested in contributors to maintain the project since I'm out of school now and have no personal use for grading Java 8 assignments haha.

But great idea! So I know originally I was a little apprehensive about including stack-traces because I was afraid of leaking test information to the students. I.e. the stack trace will include the calls that are part of our testing, not just their code, - and depending on the setup they _might_ be able to figure out things about hidden tests we didn't want them to find out. 

Although it would be cool if this was configurable so you could turn stack-printing on or off. If you're interested I could point you to the relevant spot in the code and create a branch to do this and help a little.

But the relevant file is https://github.com/tkutcher/jgrade/blob/dev/src/main/java/com/github/tkutche1/jgrade/gradedtest/GradedTestListener.java . That very bottom method is where we intercept a failed test. If you look at the JUnit API for Failure we can get the trace in that object - https://junit.org/junit4/javadoc/4.12/org/junit/runner/notification/Failure.html#getTrace() . But (for reasons I mentioned earlier, not 100% sure if they are valid or not), this should at least be something that can be disabled.

Thanks for the report.

Cheers,

Tim

**Comment by benhannel** [comment]
Thanks for the really in depth reply! I've graduated as well at this point, so I'm afraid I can no longer use the feature. It was a really useful framework for running our class - thanks for making it :)

Hope you're well.
